### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by aladshaw3** [aladshaw3/pjfnk_matlab#1]
- [x] Add line-search method to Newton methods
- [x] Add PJFNK method with the following options
- - [x] gmres
- - [x] pcg
- - [x] bicgstab
- - [x] minres
- ..... others
- [x] Add tests with preconditioners
- [x] Add more non-linear tests with new preconditioner function args
- [x] Add `equilibriate` and `dissect` function option for using actual jacobian matrix
      - https://www.mathworks.com/help/matlab/math/iterative-methods-for-linear-systems.html
      - Make a `NewtonKrylov` method?

**Comment by aladshaw3** [comment]
Add more preconditioning options and add tracking to linear residuals.

**Comment by aladshaw3** [comment]
Issue with function handles for preconditioners is NOT resolved.
